version: '3.3'
services:
  cli:
    image: php:8.0-cli
    working_dir: /app
    entrypoint: php main.php
    command: help
    volumes:
      - ./:/app
  phpunit:
    image: php:8.0-cli
    working_dir: /app
    command: bin/phpunit
    volumes:
      - ./:/app
  composer:
    image: composer:2.0
    working_dir: /app
    command: install
    volumes:
      - ./:/app

  php:
    build: ./docker/php/
    expose:
      - 9000
    volumes:
      - ./:/app
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
